### ISSUE TITLE
questions about read file 

### ISSUE THREAD

**Issue by gaoyishu** [shao-lab/MAnorm#1]
Dear shao-lab:

I am very glad to find your tools which is help for my Chip-seq analysis. But I want to know whether the ways I get the reads file is correct.

First, I used bowtie2 to map the reads to genome and get a bam file. Then I should transfer the bam to bed. But I wonder that weather I should only preserve the unique mapped reads to bed or use all reads?

Best Regards

**Comment by hongduosun** [comment]
For traditional ChIP-seq data, it is recommended to use the unique mapped reads.

**Comment by francisfa** [comment]
Hello, there are some errors in reading the reads.bed:
```
...
INFO     11/01/2021 14:38: 37960 peaks are loaded from D0CD34_shMED16_merge.rmdup.sort.last.bam_peaks.narrowPeak
WARNING  11/01/2021 14:38: Invalid Format of Read: chr1 10051   10110   chr1    10177   10233   A00253:302:HWH3KDSXY:2:2274:3640:9361   30      +       -
Traceback (most recent call last):
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/bin/manorm", line 8, in <module>
    sys.exit(main())
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/lib/python2.7/site-packages/manorm/cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/lib/python2.7/site-packages/manorm/workflow.py", line 36, in main
    ma.load_reads(reads_file1, reads_file2, shift_size1, shift_size2)
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/lib/python2.7/site-packages/manorm/core.py", line 32, in load_reads
    self.reads1 = Reads(reads_file1, self.name1, shift_size1)
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/lib/python2.7/site-packages/manorm/lib/read.py", line 22, in __init__
    self.load_reads(path, shift)
  File "/home/slee_pkuhpc/lustre1/test/software/miniconda2/lib/python2.7/site-packages/manorm/lib/read.py", line 37, in load_reads
    self.pos[chrom].append(pos)
UnboundLocalError: local variable 'pos' referenced before assignment

```
My bed file is:
```
chr1    10051   10110   chr1    10177   10233   A00253:302:HWH3KDSXY:2:2274:3640:9361   30      +       -
chr1    10182   10245   chr1    10182   10245   A00253:302:HWH3KDSXY:2:1432:10818:36918 30      +       -
chr1    10377   10418   chr1    10377   10418   A00253:302:HWH3KDSXY:2:1259:7509:23077  30      +       -
chr1    10397   10547   chr1    10415   10565   A00253:302:HWH3KDSXY:2:2219:1090:9799   34      +       -
chr1    13044   13108   chr1    13044   13108   A00253:302:HWH3KDSXY:2:1229:31846:24862 30      +       -
chr1    13305   13362   chr1    13305   13362   A00253:302:HWH3KDSXY:2:2205:29107:27790 30      +       -
chr1    16226   16265   chr1    16226   16265   A00253:302:HWH3KDSXY:2:1274:30264:11694 31      +       -
```

**Comment by hongduosun** [comment]
I am afraid this is BEDPE not BED format.

**Comment by francisfa** [comment]
Hi, I have resolved this bug after updating the manorm version and adding `--rf bedpe` and `--pe`.
