### ISSUE TITLE
Value error: Invlaid literal

### ISSUE THREAD

**Issue by ishtiaqueh** [shao-lab/MAnorm#14]
Hi,

I was hoping to run MAnorm to assess differentially bound regions between two transcription factors. The code starts running fine but eventually runs into the following error:
Traceback (most recent call last):
  File "C:\Anaconda\envs\myenv\Scripts\manorm-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Anaconda\envs\myenv\lib\site-packages\manorm\cmdline.py", line 95, in main
    full_output=full_output, name1=name1, name2=name2, output_name=output_name)
  File "C:\Anaconda\envs\myenv\lib\site-packages\manorm\workflow.py", line 36, in main
    ma.load_reads(reads_file1, reads_file2, shift_size1, shift_size2)
  File "C:\Anaconda\envs\myenv\lib\site-packages\manorm\core.py", line 32, in load_reads
    self.reads1 = Reads(reads_file1, self.name1, shift_size1)
  File "C:\Anaconda\envs\myenv\lib\site-packages\manorm\lib\read.py", line 22, in __init__
    self.load_reads(path, shift)
  File "C:\Anaconda\envs\myenv\lib\site-packages\manorm\lib\read.py", line 30, in load_reads
    chrom, start, end, strand = fields[0], int(fields[1]), int(fields[2]), fields[5]
ValueError: invalid literal for int() with base 10: '9\xe7\xac\xfbeR\x98\xf1\x98e8v1E\x059\x9d9\xe7\xcc\xf1\x0c3s\xa63\x17\xcd"\x10B(2I0\x03\xc5\xecB\xa9=E=\x14R\xe4\x9bI\xf6\x18]\xa87'

**Comment by hongduosun** [comment]
What format is your reads file?  It looks like a compressed file, BAM or ?
