### ISSUE TITLE
Error when loading MACS2 output with broad peaks called

### ISSUE THREAD

**Issue by michael-kotliar** [shao-lab/MAnorm#15]
If MACS2 was run in a broad peak mode, the output XLS file cannot be properly loaded in  Manorm as macs2 format.

Header of the input XLS file
```
chr start end length pileup -log10(pvalue) fold_enrichment -log10(qvalue) name
```
Log
```
Running MAnorm v1.2.0
Command-line arguments: --p1 /var/lib/cwl/stg65a0e4e7-d015-4ba8-a376-3f79467be976/b4f87789-e866-11e3-9546-ac162d784858_macs_peaks.xls --p2 /var/lib/cwl/stga5270828-57b3-438c-b224-9def060ef2da/
==== INFO ====
Sample 1 name = sample_1
Sample 1 peak file = /var/lib/cwl/stg65a0e4e7-d015-4ba8-a376-3f79467be976/b4f87789-e866-11e3-9546-ac162d784858_macs_peaks.xls [macs2]
Sample 1 read file = /var/lib/cwl/stgf1876471-b04e-46fb-a876-216313d998cb/b4f87789-e866-11e3-9546-ac162d784858.bam [bam]
Sample 1 read shift size = 100
Sample 2 name = sample_2
Sample 2 peak file = /var/lib/cwl/stga5270828-57b3-438c-b224-9def060ef2da/b4f88c4d-e866-11e3-9546-ac162d784858_macs_peaks.xls [macs2]
Sample 2 read file = /var/lib/cwl/stg9d33e667-16a4-47c2-80d0-16885c4063aa/b4f88c4d-e866-11e3-9546-ac162d784858.bam [bam]
Sample 2 read shift size = 100
Paired-end mode: off
Window size = 2000
Summit distance cutoff = 500
Number of random simulation = 10
M-value cutoff = 1.0
P-value cutoff = 0.01
Output directory = /bkUINY
==== Running ====
Step 1: Loading input data
Loading peaks of sample 1
Traceback (most recent call last):
  File "/usr/local/bin/manorm", line 11, in <module>
    load_entry_point('MAnorm==1.2.0', 'console_scripts', 'manorm')()
  File "/usr/local/lib/python2.7/dist-packages/manorm/cli.py", line 125, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/manorm/application.py", line 155, in run
    peaks1, peaks2, reads1, reads2 = self.load_input_data()
  File "/usr/local/lib/python2.7/dist-packages/manorm/application.py", line 120, in load_input_data
    peaks1 = peak.load_peaks(path=self.peak_file1, format=self.peak_format, name=self.name1)
  File "/usr/local/lib/python2.7/dist-packages/manorm/peak/__init__.py", line 200, in load_peaks
    for chrom, start, end, summit in peak_parser.parse():
  File "/usr/local/lib/python2.7/dist-packages/manorm/peak/parsers.py", line 81, in parse
    raise InvalidFormatError(format=self.format, line=line, line_num=line_num)
manorm.exceptions.InvalidFormatError: Invalid MACS2 format at line 27: u'chr1\t3003568\t3003935\t368\t5.57\t3.68364\t3.26515\t1.72100\tb4f87789-e866-11e3-9546-ac162d784858_macs_peak_1'
```

**Comment by hongduosun** [comment]
If you run MACS2 in a broad mode, the `summit` column in XLS is omitted.  MAnorm v1.3.0  has a  broardpeak format to handle this.
