### ISSUE TITLE
Broad peak format is not supported

### ISSUE THREAD

**Issue by michael-kotliar** [shao-lab/MAnorm#16]
Log with errors
```
Running MAnorm v1.2.0
Command-line arguments: --p1 /var/lib/cwl/stg86a89bb4-d11d-43c4-811d-d94f3648c581/b4f87789-e866-11e3-9546-ac162d784858_macs_peaks.broadPeak --p2 /var/lib/cwl/stgd4adfb7c-8939-4d52-816a-6ba7049
==== INFO ====
Sample 1 name = sample_1
Sample 1 peak file = /var/lib/cwl/stg86a89bb4-d11d-43c4-811d-d94f3648c581/b4f87789-e866-11e3-9546-ac162d784858_macs_peaks.broadPeak [broadpeak]
Sample 1 read file = /var/lib/cwl/stg8fd74aad-004f-411b-a36e-135cd608b7c4/b4f87789-e866-11e3-9546-ac162d784858.bam [bam]
Sample 1 read shift size = 100
Sample 2 name = sample_2
Sample 2 peak file = /var/lib/cwl/stgd4adfb7c-8939-4d52-816a-6ba70498673b/b4f88c4d-e866-11e3-9546-ac162d784858_macs_peaks.broadPeak [broadpeak]
Sample 2 read file = /var/lib/cwl/stg80d8b425-db19-469d-aafe-9e547b03c113/b4f88c4d-e866-11e3-9546-ac162d784858.bam [bam]
Sample 2 read shift size = 100
Paired-end mode: off
Window size = 2000
Summit distance cutoff = 500
Number of random simulation = 10
M-value cutoff = 1.0
P-value cutoff = 0.01
Output directory = /jUbyWb
==== Running ====
Step 1: Loading input data
Loading peaks of sample 1
Traceback (most recent call last):
  File "/usr/local/bin/manorm", line 11, in <module>
    load_entry_point('MAnorm==1.2.0', 'console_scripts', 'manorm')()
  File "/usr/local/lib/python2.7/dist-packages/manorm/cli.py", line 125, in main
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/manorm/application.py", line 155, in run
    peaks1, peaks2, reads1, reads2 = self.load_input_data()
  File "/usr/local/lib/python2.7/dist-packages/manorm/application.py", line 120, in load_input_data
    peaks1 = peak.load_peaks(path=self.peak_file1, format=self.peak_format, name=self.name1)
  File "/usr/local/lib/python2.7/dist-packages/manorm/peak/__init__.py", line 199, in load_peaks
    raise UnsupportedFormatError(format=format)
manorm.exceptions.UnsupportedFormatError: Unsupported format: 'broadpeak'
```

**Comment by hongduosun** [comment]
The `broadpeak` format is supported in MAnorm v1.3.0.
