### ISSUE TITLE
MAnorm 1.3

### ISSUE THREAD

**Issue by AntonioAhn** [shao-lab/MAnorm#19]
Hello, 

I am testing out MAnorm 1.3 and I am getting this error: **manorm: error: the following arguments are required: --p1/--peak1, --p2/--peak2, --r1/--read1, --r2/--read2**

I tested this out with the test data files in MAnorm/tests/data using the code: 
manorm –-p1 H1hescH3k4me3Rep1_peaks.xls –-p2 K562H3k4me3Rep1_peaks.xls –-r1 H1hescH3k4me3Rep1_reads.bed –-r2 K562H3k4me3Rep1_reads.bed -o output_file

I was wondering if this is a bug or my own error? 

kind regards,
Antonio

**Comment by hongduosun** [comment]
Hi Antonio, you mistakenly have –- in the prefix, change to -- should work.

**Comment by AntonioAhn** [comment]
oh yes! my mistake. Thanks so much for the correction!!

**Comment by wan230114** [comment]
Hi, I also got an error. But can't find the reason.

```bash
$ manorm --p1 H1hescH3k4me3Rep1_peaks.xls --p2 K562H3k4me3Rep1_peaks.xls --r1 H1hescH3k4me3Rep1_reads.bed --r2 K562H3k4me3Rep1_reads.bed -o output_file
Running MAnorm 1.3.0
==== Arguments ====
Sample 1 name = H1hescH3k4me3Rep1_peaks
Sample 1 peak file = /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/H1hescH3k4me3Rep1_peaks.xls [bed]
Sample 1 read file = /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/H1hescH3k4me3Rep1_reads.bed [bed]
Sample 1 read shift size = 100
Sample 2 name = K562H3k4me3Rep1_peaks
Sample 2 peak file = /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/K562H3k4me3Rep1_peaks.xls [bed]
Sample 2 read file = /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/K562H3k4me3Rep1_reads.bed [bed]
Sample 2 read shift size = 100
Paired-end mode: off
Window size = 2000
Summit distance cutoff = 500
Number of random simulation = 10
M-value cutoff = 1.0
P-value cutoff = 0.01
Output directory = /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/output_file
==== Running ====
Step 1: Loading input data
Loading peaks of sample 1
Loading peaks from /work/users/chenjun/Works/DYQ/meRIP_DYQ_control-treat-m6A_QZP-2021-06-23-01/01.run_callPeak/peak/test_manorm/MAnorm/tests/data/H1hescH3k4me3Rep1_peaks.xls [bed]
Traceback (most recent call last):
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/region/parsers.py", line 77, in parse
    yield self._parse_line(line)
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/region/parsers.py", line 97, in _parse_line
    start = int(fields[1])
ValueError: invalid literal for int() with base 10: 'start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/bin/manorm", line 33, in <module>
    sys.exit(load_entry_point('MAnorm==1.3.0', 'console_scripts', 'manorm')())
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/cli.py", line 306, in main
    run(args)
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/cli.py", line 273, in run
    peaks1, peaks2, reads1, reads2 = load_input_data(args)
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/cli.py", line 209, in load_input_data
    name=args.name1)
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/region/__init__.py", line 338, in load_manorm_peaks
    for chrom, start, end, summit in parser.parse(path):
  File "/home/chenjun/software/linux_tools/miniconda3/envs/manorm/lib/python3.7/site-packages/MAnorm-1.3.0-py3.7.egg/manorm/region/parsers.py", line 80, in parse
    line_num=line_num, line=line)
manorm.exceptions.FileFormatError: Invalid BED format at line 2: 'chr\tstart\tend\tlength\tsummit\ttags'
```

```bash
$ manorm -v
MAnorm 1.3.0
```

**Comment by wan230114** [comment]
Well, thanks, I solved the problem and added parameters: `--pf macs`.

```bash
manorm \
    --pf macs \
    --p1 H1hescH3k4me3Rep1_peaks.xls --p2 K562H3k4me3Rep1_peaks.xls \
    --r1 H1hescH3k4me3Rep1_reads.bed --r2 K562H3k4me3Rep1_reads.bed \
    -o output_file
```

**Comment by francisfa** [comment]
Hi, wan230114,
where did you find the `--pf macs` ?

**Comment by wan230114** [comment]
```bash
$ manorm -h
usage: manorm [-h] [-v] --p1 FILE --p2 FILE [--pf FORMAT] --r1 FILE --r2 FILE
              [--rf FORMAT] [--n1 NAME] [--n2 NAME] [--s1 N] [--s2 N] [--pe]
              [-w LENGTH] [--summit-dis DISTANCE] [--n-random NUM] [-m FLOAT]
              [-p FLOAT] [-o DIR] [--wa] [--verbose]

MAnorm -- A robust model for quantitative comparison of ChIP-seq data sets

Citation:
  Shao Z, Zhang Y, Yuan GC, Orkin SH, Waxman DJ. MAnorm: a robust model 
  for quantitative comparison of ChIP-Seq data sets. Genome biology. 
  2012 Mar 16;13(3):R16. https://doi.org/10.1186/gb-2012-13-3-r16

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         show program's version number and exit
  --verbose             Enable verbose log messages.

Input Options:
  --p1 FILE, --peak1 FILE
                        Peak file of sample 1.
  --p2 FILE, --peak2 FILE
                        Peak file of sample 2.
  --pf FORMAT, --peak-format FORMAT
                        Format of the peak files. Support ['bed',
                        'bed3-summit', 'macs', 'macs2', 'narrowpeak',
                        'broadpeak']. Default: bed
...
```

**Comment by francisfa** [comment]
Thank you for your reply. And I need to update the version.
